[main]
# The default PPD profile
default=balanced
battery_detection=true
sysfs_acpi_monitor=false

[profiles]
# PPD = TuneD
power-saver=laptop-ac-powersaver-cachyos
balanced=laptop-ac-balanced-cachyos
performance=throughput-performance-cachyos

[battery]
# PPD = TuneD
power-saver=laptop-battery-powersaver-cachyos
balanced=battery-balanced-cachyos
performance=balanced-cachyos
